name: Actions testing

env: 
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
  REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  Z_IMAGE_TAGS: s390x-${{ github.sha }}
  X_IMAGE_TAGS: amd64-${{ github.sha }}
  MANIFEST_IMAGE_TAG: manifest-${{ github.sha }}
  ROX_CENTRAL_ADDRESS: ${{ secrets.ROX_ADDRESS }}
  ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}

  IMAGE_REGISTRY: quay.io/mmondics
  APP_NAME: nationalparks
  MANIFEST_NAME: nationalparks-manifest
  
on: push

jobs:

  acs-image-scan: 
    name: Scan container manifest with Red Hat Advanced Cluster Security
    runs-on: ubuntu-latest
    environment: openshift
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    
    steps:
    - name: install roxctl cli and scan manifest
      id: step1
      run: | 
        curl -O https://mirror.openshift.com/pub/rhacs/assets/4.1.0/bin/Linux/roxctl
        chmod +x roxctl
        TOKEN=${{ env.ROX_API_TOKEN }}
        ./roxctl --insecure-skip-tls-verify image check --endpoint ${{ env.ROX_CENTRAL_ADDRESS }} --image quay.io/mmondics/nationalparks-manifest:manifest-650159e39257e45ea5a528950c48a92a94e0f6ee
 
  test-job:
    runs-on: ubuntu-latest
    needs: acs-image-scan
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo $OUTPUT1
